CC = gcc 
SRC = $(wildcard *.c)
EXEC = $(SRC:.c=) 
OBJ = $(SRC:.c=.o)

all:$(EXEC)

%.o : %.c
	$(CC) -o $@ -c $< 

$(EXEC)	: $(OBJ)
	$(CC) -o $@ $^

clean:
	rm -f *.o
	rm -f *.exe
	rm -f *.bin

exec :
	./AkramExo1.exe